# Generated by Django 3.2.13 on 2022-05-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mae', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=150)),
                ('unidade', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=60)),
            ],
        ),
    ]
